### ISSUE TITLE
3.7.0 release

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform-pattern-library#133]
- PL is currently at 3.7.0-rc-1 in Client, it should possible go to 3.7.0.
- The develop and master branches appear to be dissociated though perhaps this is just waiting on 3.7.0

**Comment by jshorland** [comment]
@willdoran what should we do with this?

**Comment by willdoran** [comment]
@jshorland I would flag this for @middle8media @justinscherer 
At the moment, we're pointing at 3.7.0-rc-1, it would be ideal to move it to 3.7.0 or 3.7.1 as is appropriate for PL. This is not critical or even important and can be handled at the next release I just wanted to flag it for reference.

**Comment by middle8media** [comment]
I plan to take care of this before or at the next release.
