### ISSUE TITLE
Refactor Categories Layout

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform-pattern-library#141]
Setting -> Categories 

Layout should follow the design pattern for Fieldset of checkboxes as outlined [here](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/3_modules/). 

Sub-categories should be indented (but trash bin icons should stay aligned.

**Comment by middle8media** [comment]
@justinscherer this is our [current UI](http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/settings-categories.html) for Categories which uses a common pattern. I am not confident integrating Fieldset Checkboxes here and I suggest we keep it as is for consistency. Thoughts?

**Comment by justinscherer** [comment]
@middle8media @crcommons I think we're going to refactor categories UI in a more meaningful way as part of 2chaguzi, so let's hold for now.
