### ISSUE TITLE
Checkboxes are misaligned in category selection in posts and when creating a category-fieldtype

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-pattern-library#144]
There is a 16px left-padding that misaligns the checkboxes for categories in create-post-view and create category field-type. Can be seen in the category-markup-branch on platform-client and on staging: http://qa.category-markup.ushahidilab.com/

![screen shot 2017-09-04 at 09 42 08](https://user-images.githubusercontent.com/8624777/30016437-6b41d51c-9155-11e7-8775-b3e86598a3bb.png)
![screen shot 2017-09-04 at 09 42 32](https://user-images.githubusercontent.com/8624777/30016454-7a14c158-9155-11e7-9175-d827202dd166.png)

**Comment by middle8media** [comment]
I pushed a fix for this [here](https://github.com/ushahidi/platform-pattern-library/commits/master)

You just need to adjust `ushahidi-platform-pattern-library` to match the version prerelease in the client package.json and pull in the styles.
