### ISSUE TITLE
Error alert pushes other elements causing alignment issues in forms

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform-pattern-library#145]
Steps to reproduce: 
Make a mistake while trying to add an email, password, post title, or any other field.

![Screen Shot 2017-09-05 at 10.38.37 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5940898e29d5f5001ab2826d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6454f66b7191a379ef0c2859415c49bc30254d58eeb9cb74fce36f34985619e8d9655871c73c19feee831bbd03ec768b4f84e5bb8b19c4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be54b50ad113364e675326e0a.png)

**Comment by rowasc** [comment]
@middle8media , this is the issue we discussed yesterday.

**Comment by rowasc** [comment]
FYI @jshorland

**Comment by middle8media** [comment]
Thanks @rowasc This should be a quick fix, I will push today.

**Comment by middle8media** [comment]
@rowasc fixed. Running `npm install ushahidi-platform-pattern-library` in the client will pull in version 3.7.1-rc.19 of the PL.

**Comment by rowasc** [comment]
Thank you Seth! I'll test and get back to you.

**Comment by rowasc** [comment]
Hi Seth. Thanks for handling this.  I see it's fixed in the login screen, but it's still broken for post fields and other forms.  Maybe it's a different issue for each?

**Comment by middle8media** [comment]
Yeah, it could be a different issue for each. I will figure out a better fix.

**Comment by middle8media** [comment]
this is fixed and in `develope`. Closing.
