### ISSUE TITLE
Misaligned text in bug-icon-badge

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-pattern-library#179]
The text in bug-icons are misaligned:
![screen shot 2018-02-07 at 16 58 27](https://user-images.githubusercontent.com/8624777/35926315-26a39532-0c28-11e8-88f8-845a79d39152.png)

**Comment by muchirijane** [comment]
Hey @Angamanga if this issue is still open could I work on it.

**Comment by Sunairaa** [comment]
Hey @Angamanga , I am outreachy candidate, i would like to work on this issue. is this issue still available?

**Comment by Angamanga** [comment]
@muchirijane @Sunairaa This issue is already fixed. Look here for new issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 🙏
