### ISSUE TITLE
The dropdown-arrow is rotated the wrong way

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform-pattern-library#180]
The dropdown-arrow is rotated the wrong way in some places:

 
![screen shot 2018-02-07 at 17 01 03](https://user-images.githubusercontent.com/8624777/35926468-82b5aebe-0c28-11e8-9257-9a08ceac5679.png)

**Comment by LizzyKate** [comment]
> The dropdown-arrow is rotated the wrong way in some places:
> 
> ![screen shot 2018-02-07 at 17 01 03](https://user-images.githubusercontent.com/8624777/35926468-82b5aebe-0c28-11e8-9257-9a08ceac5679.png)

Can I be assigned to work on this issue.

**Comment by Angamanga** [comment]
@LizzyKate This issue is outdated, closing it. Please have a look here for other issues: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22
