### ISSUE TITLE
Missing spacing between header and menu?

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#19]
https://www.dropbox.com/s/q78rsw9zlx0axwt/Screenshot%202015-11-16%2015.04.28.png?dl=0

URL: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-list.html
Browser: Firefox

**Comment by brandonrosage** [comment]
This is actually a bug with the dynamic header -- not how it renders in Firefox. I got it.

**Comment by rjmackay** [comment]
@brandonrosage done??

**Comment by brandonrosage** [comment]
The ["global-blocks" branch](https://github.com/ushahidi/platform-pattern-library/tree/global-blocks) that @middle8media created, which folds in simple, block-level layout revisions to inch toward the "Project Mustang" layout, squashes this bug.

**Comment by jshorland** [comment]
Closing. Mustang fixes this.
