### ISSUE TITLE
Make clickable things look clickable

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform-pattern-library#190]
# Update after critique

For now, I think the best way forward on this is to only implement the changes to clickable link-text. We'll save buttons et al. for later. 

Make links:

```
font-family: Lato;
font-weight: 900; //Lato heavy 
$color-dark: $link-blue; //for white backgrounds
$color-light: $disabled-grey; // for black backgrounds. We should change this variable name
letter-spacing: 0.5px;
```

## Summary

Clickable things in our UI (i.e. links, buttons) are not usable, nor accessible for a few reasons:
1. links are styled as Lato Regular or Semibold in a dark grey, which is the same styling as all of the 
2. The "body" of buttons often does not pass accessibility on the backgrounds we use it on. 
3. We use lots of muddy grey-on-grey
4. Our buttons are styled with allcaps which are actually less readable for the human eye. 
5. We use drop shadows in several places to distinguish clickable items from a background which gives our UI an aesthetic feeling of looseness or fuzzyness, and is also not accessible. 

From a design perspective, to be WCAG AA compliant, interactive elements need to have a 4.5:1 contrast ratio with their background, be big enough for someone with fat thumbs and shaking hands to tap easily, and links must have at least 2 visual markers that call it out from normal text. 

Ideally, these changes will also increase consistency in the Front end.  

### Examples

<img width="162" alt="screen shot 2018-03-14 at 10 01 47 am" src="https://user-images.githubusercontent.com/29209303/37545913-3d8e718e-2930-11e8-89f6-12f2f01b5318.png">
^^These breadcrubms just look like text

<img width="1153" alt="screen shot 2018-03-14 at 10 00 35 am" src="https://user-images.githubusercontent.com/29209303/37545920-43e9059e-2930-11e8-876c-8c22fc2241d1.png">
^^Likewise with the labels for these rows. 

<img width="528" alt="screen shot 2018-03-14 at 9 59 37 am" src="https://user-images.githubusercontent.com/29209303/37545925-46c3ef68-2930-11e8-90c7-207f9af747df.png">
^^ It's not clear if I'm supposed to click the card background, the title, the metadata, etc. half of the text doesn't have enough contrast. 

### Solution

I used our new colour palette ( #148 ) and took what we already have, rationalized it, simplified it down to it's most basic components, and tested out combinations. 

#### Old styles

![old styles](https://user-images.githubusercontent.com/29209303/37546199-55a15f38-2931-11e8-8162-1c07dd54acec.png)

### New styles on a white background

![new styles on white blue buttons](https://user-images.githubusercontent.com/29209303/37546213-6143904a-2931-11e8-98a0-c89fbe96d263.png)

### New styles on a black background

![new styles on black copy](https://user-images.githubusercontent.com/29209303/37546261-9719d562-2931-11e8-9ede-16302a6c5106.png)

#### New rules:

Tappable text (i.e. links) is Lato Black in a contrasting colour with the background with `letter-spacing: 0.5px;`

We kept the square buttons, removed the shadows, made the text sentence case, carried over the rules from links, made them 10px higher, and increased the border radius on the corners from 2px to 3px to offset the harshness, and made them contrasting colours with the background. 

We now have 4 button styles instead of 7: 2 for on white, 2 for on black. Primary button is filled, secondary button is hollow. A link can be used as a tertiary CTA or as a link in a paragraph. 

Contrasting colours for black backgrounds are either our brand's gold colour for black backgrounds, black or electric blue for white backgrounds.

Except for the blue colour and the hollow buttons, none of this is is net new. The goal would be to use the visual system we have in a way that is most effective. 

I did some quick mockups of what different pages would look like with the old and new styles side by side in this [prototype](https://xd.adobe.com/view/fe480c43-df79-4387-b38a-22396df4e8de) and [spec](https://xd.adobe.com/spec/66728f1f-9a9f-4bf9-967e-3af8d489d44d).

**Comment by Erioldoesdesign** [comment]
Something to discuss in the design crit: Arrows '>' at the end of text on buttons to indicate travelling to a new section/page and indicating a clickable thing

**Comment by justinscherer** [comment]
For now, I think the best way forward on this is to only implement the changes to clickable link-text. We'll save buttons et al. for later. 

Make links:

`font-Family: Lato;
font-weight: 900; //Lato heavy 
$color-dark: $link-blue; //for white backgrounds
$color-light: $disabled-grey; // for black backgrounds. We should change this variable name
letter-spacing: 0.5px;

**Comment by Sunairaa** [comment]
Hey @Angamanga, i am an outreachy student is this issue still available?  I would love to work on this front-end issue?

**Comment by Angamanga** [comment]
Outdated so closing
