### ISSUE TITLE
Bug - Turqouise/Pale green

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#191]
#190 #148 

When reviewing the updated PL I found two instances of two different turquoise/pale green colours.

One in the slider device:
![screen shot 2018-03-19 at 14 02 09](https://user-images.githubusercontent.com/11681324/37651853-750d8f6a-2c31-11e8-85e7-6d45f7e5c5f3.png)

![screen shot 2018-03-19 at 14 02 18](https://user-images.githubusercontent.com/11681324/37651883-852d2de2-2c31-11e8-9ec0-091c7233d46e.png)

![screen shot 2018-03-19 at 15 23 47](https://user-images.githubusercontent.com/11681324/37651890-8d4000a4-2c31-11e8-8a4b-10281aa6e728.png)
![screen shot 2018-03-19 at 15 23 51](https://user-images.githubusercontent.com/11681324/37651891-8d59f6d0-2c31-11e8-9526-3561f3e956c1.png)

May be an instance of the lighten sass.

**Comment by justinscherer** [comment]
Yeah, it's a `lighten()` function in both cases. I think we'll have to leave the toggle for now. 

fixed the error messages in #203
