### ISSUE TITLE
Bug - Dark yellow in Text Area

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#192]
#190 #148 

When reviewing the updated PL I found an instance of a dark yellow:

![screen shot 2018-03-19 at 14 08 54](https://user-images.githubusercontent.com/11681324/37652035-09f943f8-2c32-11e8-8dff-59c2b7ed11f3.png)
![screen shot 2018-03-20 at 11 14 19](https://user-images.githubusercontent.com/11681324/37652042-0d6da768-2c32-11e8-9481-6fb7956facf3.png)

When clicking into (focus) on the text area items in fragments. 

Possibly another instance of darken sass.

**Comment by justinscherer** [comment]
I don't think we actually use this input field style anywhere. But in case we do, they should be: `#777777`

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/b078b48a40ff79f569d535550537293b95c97520 in `develop` branch
