### ISSUE TITLE
Bug - Yellow link text with blue dotted line in info section

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#193]
#190 #190 

When reviewing the updated PL I found in the block area instances of a yellow text link colour still present in the 'information' section of a deployment where the link text and hover line are yellow but the non-hover dotted line is the new link blue.

![screen shot 2018-03-19 at 15 25 38](https://user-images.githubusercontent.com/11681324/37652134-6f9d6de2-2c32-11e8-9a7e-d40aeed49665.png)

While the yellow on dark grey passes the colour contrast test the mixing of styles/link colour could be confusing/inconsistent.

**Comment by justinscherer** [comment]
I agree on this one Eriol. Nice catch!

#190 should fix this by making all the links white and `font-weight: 900;` `letter-spacing: 0.5px;`
