### ISSUE TITLE
Bug - New green colour on dark grey contrast

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#194]
#190 #148 

When reviewing the updated PL I found the new green colour is used on the download confirmation 'snackbars' and is at a low contrast of 2:0.
![screen shot 2018-03-19 at 15 24 35](https://user-images.githubusercontent.com/11681324/37652742-7821a486-2c34-11e8-8296-9b73cecadbe3.png)

**Comment by justinscherer** [comment]
I think it's OK in this context because the icon is not required to understand the message or its context. It's decoration, essentially. Also, the thumbs up contrasts wiht the green background, so you'd still be able to see the primary icon, just not the circle on the background.
