### ISSUE TITLE
Bug - Pale yellow on notification

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#195]
#190 #148 

When reviewing the updated PL I found a notification in 'fragments' that uses a pale yellow background colour:

![screen shot 2018-03-19 at 15 23 33](https://user-images.githubusercontent.com/11681324/37652792-a311c9a0-2c34-11e8-9813-fa5fa5bd5d2d.png)
![screen shot 2018-03-19 at 15 23 36](https://user-images.githubusercontent.com/11681324/37652793-a33a0c26-2c34-11e8-8563-3de394a6fea5.png)

Possible instance of sass lighten

**Comment by justinscherer** [comment]
fixed in #203
