### ISSUE TITLE
Bug - Pale blue in notifications

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#196]
#190 #148

When reviewing the updated PL I found an instance of a pale blue being used on a notification:
![screen shot 2018-03-19 at 15 13 21](https://user-images.githubusercontent.com/11681324/37652868-da4e0fbe-2c34-11e8-9d38-bc44dc648448.png)

Again, may be a case of lighten sass

**Comment by justinscherer** [comment]
fixed in #203
