### ISSUE TITLE
Bug - Error red icon contrast on red background

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#197]
#190 #148 

When reviewing the updated PL I found the error icon on the new red contrast problem:
![screen shot 2018-03-19 at 15 20 32](https://user-images.githubusercontent.com/11681324/37652913-ff07d9e8-2c34-11e8-9e65-529184a20102.png)

**Comment by justinscherer** [comment]
fixed in #203
