### ISSUE TITLE
Bug - Disabled button text not readable

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#198]
#190  #148 

When reviewing the updated PL I found that the disabled button text is white on pale grey (as it was before)
![screen shot 2018-03-19 at 15 16 37](https://user-images.githubusercontent.com/11681324/37653118-a76676ee-2c35-11e8-8421-278d95e025e3.png)

Might be a chance to change to a readbale state.

**Comment by justinscherer** [comment]
This is a weird one where it's actually accessible here. Things you can't click don't need to pass 4.5:1 colour contrast. The fix for this is making buttons clickable so that users can make errors and recover from them instead of disabling the buttons.
