### ISSUE TITLE
Bug - Yellow focus halo on text fields

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#200]
#190 #148

When reviewing the updated PL I found that we're using the brand yellow as a focus colour blurry border effect on text fields:

![screen shot 2018-03-19 at 15 17 13](https://user-images.githubusercontent.com/11681324/37653253-159d7dec-2c36-11e8-9d09-9344efd15dcb.png)

**Comment by justinscherer** [comment]
nice catch!

Let's replace it with `$disabled-grey` i.e. `#D0D0D0`

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/b078b48a40ff79f569d535550537293b95c97520 in `develop` branch
