### ISSUE TITLE
Bug - White loading dots on pale grey loading bar

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#201]
#190 #148

When reviewing the updated PL I found that the white dot animation in 'fragments' is shown on a pale grey background and is not visible:

![screen shot 2018-03-19 at 15 20 16](https://user-images.githubusercontent.com/11681324/37653297-4a2d6900-2c36-11e8-8b06-cebf04049df7.png)

**Comment by justinscherer** [comment]
Nice catch

Loader should be `$black`

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/b078b48a40ff79f569d535550537293b95c97520 in `develop` branch
