### ISSUE TITLE
Bug - 'Title for checkboxes' 

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform-pattern-library#202]
#190 #148

When reviewing the updated PL I found that the 'Custom fieldset' element in 'fragments' may be broken as when you click into the pale grey section the pale grey takes over the entire field:

![screen shot 2018-03-20 at 12 02 48](https://user-images.githubusercontent.com/11681324/37653442-cd6a51d4-2c36-11e8-8d87-4bf3326928b1.png)
![screen shot 2018-03-20 at 12 02 51](https://user-images.githubusercontent.com/11681324/37653443-cd8a4296-2c36-11e8-8e6f-20a1ab1f62c8.png)

Also the pale grey probably isn't high enough contrast.

(this might not be a bug so feel free to close this one if this is expected behaviour within the PL)

**Comment by justinscherer** [comment]
I would need to see how this looks with actual data in it before I can make a call on whether or not it's a mistake. With `$black` elements in the list, it'd probably pass.
