### ISSUE TITLE
refactor alert styles to remove backgrounds

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform-pattern-library#203]
## Old style:
<img width="569" alt="screen shot 2018-03-22 at 2 27 09 pm" src="https://user-images.githubusercontent.com/29209303/37796571-39e11f1c-2ddd-11e8-8ef6-6d3864f2e51b.png">

## New style

<img width="400" alt="screen shot 2018-03-22 at 2 26 58 pm" src="https://user-images.githubusercontent.com/29209303/37796586-3fd8cea6-2ddd-11e8-9cd9-bfa2bd72d02d.png">

## Changes

- [ ] remove `font-style: italic;`
- [ ] remove `border-left`
- [ ] remove `background-color`
- [ ] make error text the error red colour `#EB0202`
- [ ] do the same things for success messages, except make the color `#007A4B`
- [ ] do the same thing for warnings, except make the text `#777777`

cc @Erioldoesdesign

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/99776587e175ecd3afbfddc5b6d88ab6465f1eea in `develop` branch.
