### ISSUE TITLE
Add user button on settings/users should be an anchor element

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform-pattern-library#22]
This button is best handled as a link by the platform client. Would it be possible to change the styling so that it can be applied to <a>?

<img width="730" alt="screen shot 2015-11-29 at 22 41 35" src="https://cloud.githubusercontent.com/assets/2694405/11463034/7929172e-96ea-11e5-9f72-5605c5939eba.png">

**Comment by willdoran** [comment]
This is also true for the Edit button on the post detail page
<img width="721" alt="screen shot 2015-11-29 at 22 52 40" src="https://cloud.githubusercontent.com/assets/2694405/11463160/f504419c-96eb-11e5-8651-d321c76ed383.png">

**Comment by middle8media** [comment]
will fix markup in client as well
