### ISSUE TITLE
up/downvote functionality needed for form steps

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform-pattern-library#24]
This could be handled as a button at the top of the step tabs. This has the same behaviour as the reordering of form attributes/fields.

http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-post-type-detail.html

**Comment by middle8media** [comment]
@will does https://github.com/ushahidi/platform-pattern-library/issues/25 solve this issue?

**Comment by will** [comment]
I have no idea, sorry I can't be of more help.

**Comment by middle8media** [comment]
sorry @will I meant to @mention @willdoran

**Comment by willdoran** [comment]
@middle8media yep I think this is working
