### ISSUE TITLE
Step tabs appear clickable but are not

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#27]
https://www.dropbox.com/s/a4zpya0olc6i0ba/Screenshot%202015-12-10%2016.07.32.png?dl=0

The `<li>` for the tabs has `cursor: pointer` however only the text inside the `<a>` is clickable. This makes for a really irritating UI in practice.

Can we fix this styling so that
1. Only the actual link has a pointer cursor?
2. Ideally the `<a>` expands to fill the tab so the entire tab as actually clickable.

**Comment by middle8media** [comment]
The css is ready to go.

A slight change to the markup here - https://github.com/ushahidi/platform-pattern-library/commit/b9dcada5dedb82e32dffb8801953a302140b5b5a#diff-34b5f2524642efb362dbf2fbf3d0f7b2L119

**Comment by rjmackay** [comment]
@willdoran Can you update the client to match?
