### ISSUE TITLE
Update post edit view puts save button at the top again

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#28]
http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit-with-steps.html

This has previously been reported as an issue by users. People fail to find the "Save post" button since they expect a save button at the end of the form.
Can we add a 2nd button below the form? or in the sidebar?

**Comment by middle8media** [comment]
fixed via https://github.com/ushahidi/platform-pattern-library/commit/7f9e8e5660d6acbf333220773480a583cfc04a33

adding markup to client and submitting PR
