### ISSUE TITLE
Mismatch in save button location

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#33]
- Edit user has save at the bottom
https://www.dropbox.com/s/0pjnv7i821geami/Screenshot%202016-02-22%2016.06.21.png?dl=0
- Edit role has save at the top
https://www.dropbox.com/s/7os2d9ut3xu25rq/Screenshot%202016-02-22%2016.07.00.png?dl=0

Can we make a consistent decision about this?
Also - users have logged missing save buttons as a bug before so I think we should be showing save at the bottom.. but maybe at the top too?

**Comment by middle8media** [comment]
@brandonrosage and I have been discussing this. Here is where we landed.

forms that are five fields of fewer = button/s on bottom
forms that are more than five fields = button/s on top AND bottom

@rjmackay Does this work for the dev team?

**Comment by middle8media** [comment]
closed via https://github.com/ushahidi/platform-client/commit/c2b9b93baf42a7663be646a6f36dec812f9d2437

**Comment by rjmackay** [comment]
That makes sense - have you checked thats done everywhere? or should I keep this open and have Will review the client?

**Comment by middle8media** [comment]
yes, as far as I know it is done everywhere. I submitted a PR to @willdoran
