### ISSUE TITLE
Add a start/end date selector on Activity filter

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#39]
I'd also suggest dropping the "today, this week, this month" out of filters and make it more easily selectable. 
<img width="979" alt="screen shot 2016-05-05 at 6 11 38 pm" src="https://cloud.githubusercontent.com/assets/1618793/15061681/edf16b96-12ec-11e6-8530-1e9a5d4cd1d9.png">

**Comment by brandonrosage** [comment]
I've revised the "Activity" page example so that the "Filters" button in the toolbar reads "Date range," and displays the typical date range controls. It was previously a selection of one of three options because that's what the product currently does. And I've been called to honor those constraints. We'll see if this is possible in the next release.

**Comment by caharding** [comment]
I guess on this screen the filters box seems like an unnecessary step and
it would be better to have all of these options, not buried in a button. I
think having the 3 defaults as quick options is also nice.

On Fri, May 6, 2016 at 6:49 PM, Brandon Rosage <notifications@github.com>
wrote:

> I've revised the "Activity" page example so that the "Filters" button in
> the toolbar reads "Date range," and displays the typical date range
> controls. It was previously a selection of one of three options because
> that's what the product currently does. And I've been called to honor those
> constraints. We'll see if this is possible in the next release.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/39#issuecomment-217481320>
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
I've created an optional dynamic treatment for date range fieldsets that is appropriate for the functionality here. It's very similar to Google Analytics, but a bit simpler.

On page load:

![image](https://cloud.githubusercontent.com/assets/1136279/15121456/653bab94-15e0-11e6-854a-543ba30e3f69.png)

Upon interaction: 

![image](https://cloud.githubusercontent.com/assets/1136279/15121470/72960ef6-15e0-11e6-9ef7-1b93a85e91ae.png)

Upon selecting "custom date range":

![image](https://cloud.githubusercontent.com/assets/1136279/15121487/8a51ae2e-15e0-11e6-8cff-8a7a7aa16c36.png)


Upon inserting custom date range values:

![image](https://cloud.githubusercontent.com/assets/1136279/15121500/994f596c-15e0-11e6-8ec9-d6593d919588.png)

Upon applying the control:

![image](https://cloud.githubusercontent.com/assets/1136279/15121521/ad4dd42a-15e0-11e6-82ff-7cfefc9c3113.png)

**Comment by caharding** [comment]
Good solution. The pattern for the drop down still needs some work. The
rounded corner issue appears here again. This drop down should look like a
continuation of the button, not a separate div on a new z-axis with its own
rounded corners.

On Mon, May 9, 2016 at 8:22 PM, Brandon Rosage <notifications@github.com>
wrote:

> I've created an optional dynamic treatment for date range fieldsets that
> is appropriate for the functionality here. It's very similar to Google
> Analytics, but a bit simpler.
>
> On page load:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15121456/653bab94-15e0-11e6-854a-543ba30e3f69.png>
>
> Upon interaction:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15121470/72960ef6-15e0-11e6-9ef7-1b93a85e91ae.png>
>
> Upon selecting "custom date range":
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15121487/8a51ae2e-15e0-11e6-8cff-8a7a7aa16c36.png>
>
> Upon inserting custom date range values:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15121500/994f596c-15e0-11e6-8ec9-d6593d919588.png>
>
> Upon applying the control:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15121521/ad4dd42a-15e0-11e6-82ff-7cfefc9c3113.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/39#issuecomment-217929842>
>



-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
I agree. I've revised the popup treatment for "custom fieldsets" and "postcard" action dropdowns (likely more to come, as needed): http://d.pr/i/16rU0/3cKzqfXV
