### ISSUE TITLE
Timeline is squished and bar chart is large

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#40]
Looks funny, consider restyling

<img width="975" alt="screen shot 2016-05-05 at 6 12 55 pm" src="https://cloud.githubusercontent.com/assets/1618793/15061686/040b18f0-12ed-11e6-9241-499f3266119f.png">

**Comment by rjmackay** [comment]
Not sure its worth fixing this in the PL - since the actual graphing libs in the client are different. Though it is good to have some idea of the end goal

**Comment by caharding** [comment]
Got it

On Thursday, May 5, 2016, Robbie Mackay <notifications@github.com> wrote:

> Not sure its worth fixing this in the PL - since the actual graphing libs
> in the client are different. Though it is good to have some idea of the end
> goal
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/40#issuecomment-217328911>
>


-- 
Charlie Harding
Product Director

**Comment by brandonrosage** [comment]
Robbie is right. The graphs in the PL are placeholder images. The charting library handles its styling separately.
