### ISSUE TITLE
Settings grid is too large, make more dense

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#41]
Reduce the height of the rows here to make more dense

<img width="983" alt="screen shot 2016-05-05 at 6 13 23 pm" src="https://cloud.githubusercontent.com/assets/1618793/15061698/18e789fc-12ed-11e6-93ee-eaf9d81ce012.png">

**Comment by brandonrosage** [comment]
The consistency in spacing in the "listing-item" pattern, A, makes things easily scannable, and B, allows for a wider range of uses. For example, "[Data Sources](http://mustang.robbiemackay.com/assets/html/5_layouts/settings-data-sources.html)" uses this pattern to include an image and a trigger that exposes a body area:

![image](https://cloud.githubusercontent.com/assets/1136279/15078135/613578b0-1377-11e6-8ee2-488517a64747.png)

Visually navigating a page like that with constrained space around the content is very difficult. In the future, I'd like for each item to link to a separate view, relying less on this pattern to display as much as it does. But I'm required to fit Mustang into the existing architectural constraints. And all of those settings fitting into one view is one of them.

**Comment by caharding** [comment]
Agree it is good to use fewer patterns. The problem is how the Setting each
have a sub header which is expanding the size of the Div. Would be better
to keep the Div the same size, and just center the two lines of text within
it.

On Fri, May 6, 2016 at 6:46 PM, Brandon Rosage <notifications@github.com>
wrote:

> The consistency in spacing in the "listing-item" pattern, A, makes things
> easily scannable, and B, allows for a wider range of uses. For example, "Data
> Sources
> <http://mustang.robbiemackay.com/assets/html/5_layouts/settings-data-sources.html>"
> uses this pattern to include an image and a trigger that exposes a body
> area:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1136279/15078135/613578b0-1377-11e6-8ee2-488517a64747.png>
>
> Visually navigating a page like that with constrained space around the
> content is very difficult. In the future, I'd like for each item to link to
> a separate view, relying less on this pattern to display as much as it
> does. But I'm required to fit Mustang into the existing architectural
> constraints. And all of those settings fitting into one view is one of them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/41#issuecomment-217480684>
>



-- 
Charlie Harding
Product Director

**Comment by caharding** [comment]
It may also be nice to have a visual icon for each of these setting types.
But, definitely a nice to have not necessary.

On Fri, May 6, 2016 at 8:20 PM, Charles Harding <charles@ushahidi.com>
wrote:

> Agree it is good to use fewer patterns. The problem is how the Setting
> each have a sub header which is expanding the size of the Div. Would be
> better to keep the Div the same size, and just center the two lines of text
> within it.
>
> On Fri, May 6, 2016 at 6:46 PM, Brandon Rosage <notifications@github.com>
> wrote:
>
>> The consistency in spacing in the "listing-item" pattern, A, makes things
>> easily scannable, and B, allows for a wider range of uses. For example, "Data
>> Sources
>> <http://mustang.robbiemackay.com/assets/html/5_layouts/settings-data-sources.html>"
>> uses this pattern to include an image and a trigger that exposes a body
>> area:
>>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/1136279/15078135/613578b0-1377-11e6-8ee2-488517a64747.png>
>>
>> Visually navigating a page like that with constrained space around the
>> content is very difficult. In the future, I'd like for each item to link to
>> a separate view, relying less on this pattern to display as much as it
>> does. But I'm required to fit Mustang into the existing architectural
>> constraints. And all of those settings fitting into one view is one of them.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ushahidi/platform-pattern-library/issues/41#issuecomment-217480684>
>>
>
>
>
> --
> Charlie Harding
> Product Director
>



-- 
Charlie Harding
Product Director
