### ISSUE TITLE
Dropdown pattern seems broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#46]
Dropdown is breaking the style visual style and should be appending to the bottom of the div

<img width="263" alt="screen shot 2016-05-06 at 10 29 28 am" src="https://cloud.githubusercontent.com/assets/1618793/15081004/821d1292-1375-11e6-94b7-6e5a4c4e0301.png">

**Comment by brandonrosage** [comment]
The short story here is that, for every single dropdown/popover interaction in the product to have the same visual treatment, we have to commit to throwing out native `<select>` controls (like the one you've highlighted), and use custom controls everywhere that type of interaction occurs.

That comes at a hefty cost to the responsive web experience and accessibility. Native select controls take advantage of browsers' optimization for that control. Smartphones users, for example, typically get a smartphone-optimized `select` UX for navigating its options:

![iOS 8](http://learn.shayhowe.com/assets/images/courses/html-css/building-forms/ios-date.png)

That said, `select` controls are only effective (in my judgment) at choosing _one_ option from a list. If we need the ability to select multiple options, filter/search the options, show/hide content appended to a selected option, or display icons with the options, we need a custom control. And, increasingly with Ushahidi, there just aren't interactions that are as simple as choosing one option from a list. So the number of cases where a native `select` control is the right tool for Ushahidi is dwindling.

Therefore, I'd recommend a two-part approach to this:

1. We continue to support native `<select>` controls, and accept the inconsistency in the interest of the browser benefits and accessibility.
2. We continue to bolster the flexibility of our `custom-fieldset` pattern to handle all (or nearly all) of these make-a-selection-in-a-dropdown interactions.

**Comment by rjmackay** [comment]
@brandonrosage Is there some immediate action needed here?

**Comment by brandonrosage** [comment]
Not unless @charlie objects to my reasoning here.

**Comment by jshorland** [comment]
closing.
