### ISSUE TITLE
Add visual aid to "Add Field"

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#49]
Seems we can make this faster to visually scan if there were an icon with each. 

<img width="594" alt="screen shot 2016-05-06 at 10 37 32 am" src="https://cloud.githubusercontent.com/assets/1618793/15081205/9b5cc332-1376-11e6-9b6f-b8bd746abf5c.png">

**Comment by middle8media** [comment]
@brandonrosage I can knock this out quick, I just wanted to get your thoughts.

**Comment by Sunairaa** [comment]
Hey, @Angamanga is this issue still available? I would like to work on it.

**Comment by Angamanga** [comment]
@Sunairaa This is outdated so closing it.
