### ISSUE TITLE
Add Post Button in Footer Confusing

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform-pattern-library#5]
While adding a new post, when you get to the bottom, it is confusing that you have to click "Save" instead of the "add post" button that is in the footer. 

Maybe just take out the add post button in the footer? 

cc/ @brandonrosage

**Comment by brandonrosage** [comment]
Yeah, I think the potential confusion isn't worth the value of having the "Add post" action in more places. If anything, we benefit from having it uniformly in the header/menu.

**Comment by sophshep** [comment]
I'll take it out of PL today, then assign to @rjmackay to update client

**Comment by sophshep** [comment]
Hey @rjmackay - can you take update the footer in the client?
