### ISSUE TITLE
Cursor on mobile search does not scan right as you type until too late

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#50]
As I enter text into the search bar on a smaller screen, it takes a few words for the cursor to catch up to my text.
<img width="399" alt="screen shot 2016-05-06 at 10 41 09 am" src="https://cloud.githubusercontent.com/assets/1618793/15081297/26683cf4-1377-11e6-81df-d407313897e8.png">

**Comment by middle8media** [comment]
I am unable to recreate this, although as I enter text that is longer than the search input field the cursor does appear above "Saved Searches" and "Filters" buttons.

@brandonrosage Maybe the search input field could expand when clicking/tapping inside

**Comment by middle8media** [comment]
Is this still an issue? Does #72 fix this?

**Comment by brandonrosage** [comment]
The cursor issue was fixed in a previous commit. #72 will only make it better, as it will expand the width of the input when it's active.
