### ISSUE TITLE
Spacing at bottom of plans needs adjustment 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#51]
Self hosted is bumping up against that grassroots button 

<img width="876" alt="screen shot 2016-05-06 at 10 43 12 am" src="https://cloud.githubusercontent.com/assets/1618793/15081338/611e5b58-1377-11e6-960b-25ae77e001a7.png">

**Comment by middle8media** [comment]
This is fixed

![image](https://cloud.githubusercontent.com/assets/1033332/16868214/616ce9c2-4a44-11e6-9ae2-e87490962043.png)
