### ISSUE TITLE
Timeline checkbox not correctly aligned 

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#57]
The checkbox and title seem to be misaligned 
![img_3673](https://cloud.githubusercontent.com/assets/1618793/15335845/c5780022-1c28-11e6-9a7d-242e06f8981f.jpg)

**Comment by middle8media** [comment]
@caharding are you referring to the horizontal alignment of the checkbox and the post title?

![image](https://cloud.githubusercontent.com/assets/1033332/16854695/14304082-49e0-11e6-80ba-b6fe7553cba8.png)

If so, this would be the proper alignment

![image](https://cloud.githubusercontent.com/assets/1033332/16854761/6d72112a-49e0-11e6-8668-6ce5c11a9e0d.png)

**Comment by caharding** [comment]
Looks fine now

On Thu, Jul 14, 2016 at 4:32 PM, Seth Hall <notifications@github.com> wrote:

> @caharding <https://github.com/caharding> are you referring to the
> horizontal alignment of the checkbox and the post title?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1033332/16854695/14304082-49e0-11e6-80ba-b6fe7553cba8.png>
>
> If so, this would be the proper alignment
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1033332/16854761/6d72112a-49e0-11e6-8668-6ce5c11a9e0d.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/57#issuecomment-232783518>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaUFQmPUP9SaebaPP66PmNJNTF_Crks5qVpzFgaJpZM4Igm3I>
> .
>



-- 
Charlie Harding
Product Director
