### ISSUE TITLE
Deployment overview dropdown fades to white on mobile

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#58]
On mobile browse to map mode, then click on the dropdown for the deployment overview. There is a weird white animation that occurs that seems like an error
![img_3675](https://cloud.githubusercontent.com/assets/1618793/15336006/4f99a92c-1c29-11e6-9863-f28c8a6600fd.jpg)

**Comment by middle8media** [comment]
@brandonrosage didn't we discuss this a while back? Are you able to pinpoint this visual bug with ease?

**Comment by rjmackay** [comment]
@brandonrosage is this fixed?
