### ISSUE TITLE
How to post will be buried if there are too many post types/surveys

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform-pattern-library#61]
The mode context bar doesn't scroll, so the how to post is buried

<img width="1278" alt="screen shot 2016-05-17 at 1 33 57 pm" src="https://cloud.githubusercontent.com/assets/1618793/15338268/1325f30a-1c34-11e6-88d8-161b107e9686.png">

**Comment by rjmackay** [comment]
Related: if there are too many post types they can drop off the bottom of the screen.
