### ISSUE TITLE
Weird white bar in header on smaller screens

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#63]
![screenshot 2016-05-25 15 52 31](https://cloud.githubusercontent.com/assets/7965/15527707/d69e28f4-2290-11e6-9a61-917fc3f14bd3.png)

**Comment by middle8media** [comment]
@rjmackay: @brandonrosage and I are not able to replicate this. Can you replicate it again and let us know the details (mobile device, browser, etc...) Thanks.

**Comment by rjmackay** [comment]
I'm seeing this on both chrome and firefox with a small browser window.
Weirdly I don't see it in firefox responsive design view.. but a normal narrow browser window does show it.

**Comment by middle8media** [comment]
Looking into it.

**Comment by brandonrosage** [comment]
I still can't replicate it with the conditions Robbie mentioned.

**Comment by brandonrosage** [comment]
I fixed this just now.
