### ISSUE TITLE
More menu `tuck` items position

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform-pattern-library#70]
`.tuck` items ("Tasks" and "Settings") are positioned absolute bottom.

![image](https://cloud.githubusercontent.com/assets/1033332/16869457/e64d6896-4a4a-11e6-9b0f-6c8d82480778.png)

I suggest they fall inline with the items in account menu

![image](https://cloud.githubusercontent.com/assets/1033332/16869561/652dcd4a-4a4b-11e6-9916-43831fca2179.png)

**Comment by brandonrosage** [comment]
Fixed in `architecture`
