### ISSUE TITLE
Update location filter from PL

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform-pattern-library#79]
Currently we have this in the client: https://www.dropbox.com/s/iwoowh7hxfcvh41/Screenshot%202016-08-04%2016.21.59.png?dl=0

Can we include this in the PL filters??

**Comment by brandonrosage** [comment]
I've staged this in the PL -- currently in the `architecture` branch.

![filter](https://cloud.githubusercontent.com/assets/1136279/17595438/b330ce80-5fb2-11e6-9bd8-a128824b359c.png)

**Comment by rjmackay** [comment]
@brandonrosage this might seem a little insane.. but could we try making changes like this on their own branches? ie. a `location-search-fieldset` branch just for this change.
This would allow dev's to grab just the change they needed, implement it in the client and merge it to `master` of the PL.. without accidentally grabbing other changes along with it.
