### ISSUE TITLE
Map overlay appears in front of client parallax

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform-pattern-library#9]
Both the map buttons and Leaflet label at the bottom right appear in front of the parallax.

<img width="935" alt="screen shot 2015-11-09 at 22 01 39" src="https://cloud.githubusercontent.com/assets/2694405/11053258/a6d52c66-872d-11e5-9658-d00783639718.png">

**Comment by rjmackay** [comment]
You might need to fix that in the client CSS overrides, or just update the
PL. It'll be a z-index mismatch between leaflet css and the PLL.

On Tue, Nov 10, 2015 at 4:04 PM, will <notifications@github.com> wrote:

> Both the map buttons and Leaflet label at the bottom right appear in front
> of the parallax.
>
> [image: screen shot 2015-11-09 at 22 01 39]
> <https://cloud.githubusercontent.com/assets/2694405/11053258/a6d52c66-872d-11e5-9658-d00783639718.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform-pattern-library/issues/9>.
>



-- 
Robbie Mackay

Head of engineering
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by willdoran** [comment]
Ok groovy I'll move the issue.
